# Runs benchmarks.

on:
  pull_request:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  BASELINE: base
  SEED: alloy-trie

name: bench
jobs:
  codspeed:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Secure runner
        uses: tempoxyz/gh-actions/actions/secure-runner@117919c943b804057be733b0c4034c5542e58959
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: rui314/setup-mold@v1
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          cache-bin: false
      - name: Install cargo-codspeed
        uses: taiki-e/install-action@3f74d7c16a4242f1c95561e98edc25d36adb4375 # v2.87.12
        with:
          tool: cargo-codspeed
      - name: Build the benchmark target(s)
        run: cargo codspeed build --profile profiling --features="arbitrary"
      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: cargo codspeed run --workspace
          token: ${{ secrets.CODSPEED_TOKEN }}
